import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'

export default function Home() {

  const [salahTimings, setSalahTimings] = useState({
    fajr: '',
    dhuhr: '',
    asr: '',
    maghrib: '',
    isha: '',
    sunrise: '',
    sunset: ''
  });

  useEffect(() => {

    if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition((position) => {

        let date_obj = new Date();
        let month = date_obj.getMonth();
        let year = date_obj.getFullYear();
        let latitude = position.coords.latitude;
        let longitude = position.coords.longitude;

        fetch(`https://api.aladhan.com/v1/calendar?latitude=${latitude}&longitude=${longitude}&method=9&month=${month + 1}&year=${year}`)
          .then(response => response.json())
          .then(data => {
            
            let date = date_obj.getDate();

            setSalahTimings((prev) => {
              return {
                ...prev,
                fajr: data.data[date - 1].timings.Fajr,
                dhuhr: data.data[date - 1].timings.Dhuhr,
                asr: data.data[date - 1].timings.Asr,
                maghrib: data.data[date - 1].timings.Maghrib,
                isha: data.data[date - 1].timings.Isha,
                sunrise: data.data[date - 1].timings.Sunrise,
                sunset: data.data[date - 1].timings.Sunset
              }
            })
          })
          .catch(err => console.log(err))
      }, (error) => console.log(error))
    } else {
      console.log('not supported');
    }

  }, [])

  return (
    <div className={styles.container}>
      {Object.keys(salahTimings).map((key, index) => {
        return (
          <div key={index}>{salahTimings[key]}</div>
        )
      })}
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
